// packages/reactivity-adapters/solid/src/index.ts
import { createReactivityAdapter } from '@signaldb/core'
import { createSignal, getOwner, onCleanup } from 'solid-js'

const solidReactivityAdapter = createReactivityAdapter({
  create: () => {
    const [depend, rerun] = createSignal(undefined, { equals: false })
    return {
      depend: () => {
        depend()
      },
      notify: () => {
        rerun()
      },
    }
  },
  isInScope: () => !!getOwner(),
  onDispose: (callback) => {
    onCleanup(callback)
  },
})

export default solidReactivityAdapter

// packages/reactivity-adapters/angular/src/index.ts
import { signal, untracked } from '@angular/core'
import { createReactivityAdapter } from 'signaldb'

const angularReactivityAdapter = createReactivityAdapter({
  create: () => {
    const dep = signal(0)
    return {
      depend: () => {
        dep()
      },
      notify: () => {
        dep.set(untracked(() => dep() + 1))
      },
    }
  },
})

export default angularReactivityAdapter
