// packages/plugin-solid/src/index.ts
import {
  createSignal,
  onCleanup,
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
} from 'solid-js/dist/solid'
import { createReactivityAdapter } from 'signaldb'

/**
 * Reactivity adapter for Solid. See https://signaldb.js.org/reactivity/solid/ for more information.
 */
export const solidReactivityAdapter = createReactivityAdapter({
  create: () => {
    const [depend, rerun] = createSignal(undefined, { equals: false })
    return {
      depend: () => {
        depend()
      },
      notify: () => {
        rerun()
      },
    }
  },
  isInScope: undefined,
  onDispose: (callback) => {
    onCleanup(callback)
  },
})

export default solidReactivityAdapter

// packages/plugin-angular/src/index.ts
import { signal, untracked } from '@angular/core'
import { createReactivityAdapter } from 'signaldb'

/**
 * Reactivity adapter for Angular. See https://signaldb.js.org/reactivity/angular/ for more information.
 */
export const angularReactivityAdapter = createReactivityAdapter({
  create: () => {
    const dep = signal(0)
    return {
      depend: () => {
        dep()
      },
      notify: () => {
        dep.set(untracked(() => dep() + 1))
      },
    }
  },
})

export default angularReactivityAdapter
